// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

module.exports = async function main(driver) {
    if (!driver) {
        console.error("TC-GA Error: Driver Not Found");
        return;
    }

    await driver.get("https://hihimoodle.gnomio.com/my/")
    await driver.manage().window().setRect({ width: 1387, height: 1040 })
    await driver.findElement(By.css(".event-action > .list-group-item-action")).click()
    {
      const element = await driver.findElement(By.css("#page-mod-assign-grader > div:nth-child(1)"))
      await driver.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '1 <p>1</p>'}", element)
    }
    const gradeassignment = await fs.readFileSync(
        "data/gradeassignment.txt",
        "utf-8"
      );
    const gradeassignmentArray = gradeassignment.split("\r\n");
      
    for (let i = 0; i < gradeassignmentArray.length; i++) {
        const gradeData = gradeassignmentArray[i].split(":")[1].split(";");
        const grade = gradeData[0];
        const cmt = gradeData[1];
        const gradeStatus = gradeData[2];
        if (grade && gradeStatus === "success"){
            console.log(`TC-GA-00${i + 1}: Passed`);
        }else {
            console.log(`TC-GA-00${i + 1}: Passed`);
        }
    }
    
    await driver.findElement(By.id("id_assignfeedbackcomments_editoreditable")).click()
    await driver.findElement(By.css("p")).click()
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">Y</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You&nbsp;</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You d</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You di</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You d</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You&nbsp;</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You đ</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You đi</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You đ</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You&nbsp;</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You d</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You di</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You did</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You did&nbsp;</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You did n</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You did no</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You did not</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You did noth</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You did nothi</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You did nothin</p>")
    await driver.findElement(By.id("id_assignfeedbackcomments_editor")).sendKeys("<p dir=\"ltr\" style=\"text-align: left;\">You did nothing</p>")
    {
      const element = await driver.findElement(By.id("id_assignfeedbackcomments_editoreditable"))
      await driver.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p dir=\"ltr\" style=\"text-align: left;\" id=\"yui_3_17_2_1_1671440595541_1127\">You did nothing</p>'}", element)
    }
    await driver.findElement(By.id("id_grade")).click()
    await driver.findElement(By.id("id_grade")).sendKeys("0")
    await driver.findElement(By.id("yui_3_17_2_1_1671440595541_1199")).click()
    {
      const element = await driver.findElement(By.css(".searchcommentsbutton"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".searchcommentsbutton"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("yui_3_17_2_1_1671440595541_2355")).click()
    await driver.executeScript("window.scrollTo(0,88)")
    await driver.executeScript("window.scrollTo(0,397)")
    await driver.findElement(By.linkText("O")).click()
    await driver.executeScript("window.scrollTo(0,166)")
    await driver.findElement(By.linkText("All")).click()
    await driver.findElement(By.linkText("Grade")).click()
    {
      const element = await driver.findElement(By.id("yui_3_17_2_1_1671440634137_686"))
      await driver.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '1 <p>1</p>'}", element)
    }
    await driver.findElement(By.id("id_grade")).click()
    await driver.findElement(By.id("id_grade")).sendKeys("90")
    await driver.findElement(By.id("yui_3_17_2_1_1671440634137_1154")).click()
  
  
}
